spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:meetingroom
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /openapi.yaml
